import type { NextPage } from 'next'
import Head from 'next/head';
import Script  from 'next/script';
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import { TextField,Button } from '@mui/material';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
      <TextField variant="outlined" size="small" sx={{input:{height:15,backgroundColor:'white'}}}  id="name"   placeholder="Category Name"  />
      <Button  type="submit" variant="contained"  color="primary">Submit</Button>
      </main>
    </div>
  );
}

export default Home;
